apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dk-argo-app
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
  source:
    repoURL: https://github.com/d2201/argo-charts.git
    path: app
    targetRevision: HEAD