apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
spec:
  selector:
    app: {{ .Values.app_name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-canary
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
spec:
  selector:
    app: {{ .Values.app_name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3100